"""Goods receipt API schemas."""

from app.goods_receipt.schemas.goods_receipt import (
    GoodsReceiptAttachmentResponse,
    GoodsReceiptAttachmentWrite,
    GoodsReceiptCreate,
    GoodsReceiptEwayBillWrite,
    GoodsReceiptImportRequest,
    GoodsReceiptLineResponse,
    GoodsReceiptLineWrite,
    GoodsReceiptListFilters,
    GoodsReceiptNoteResponse,
    GoodsReceiptNoteType,
    GoodsReceiptNoteWrite,
    GoodsReceiptPurchaseOrderReport,
    GoodsReceiptRegisterRecord,
    GoodsReceiptResponse,
    GoodsReceiptStatus,
    GoodsReceiptSummary,
    GoodsReceiptUpdate,
)

__all__ = [
    "GoodsReceiptAttachmentResponse",
    "GoodsReceiptAttachmentWrite",
    "GoodsReceiptCreate",
    "GoodsReceiptEwayBillWrite",
    "GoodsReceiptImportRequest",
    "GoodsReceiptLineResponse",
    "GoodsReceiptLineWrite",
    "GoodsReceiptListFilters",
    "GoodsReceiptNoteResponse",
    "GoodsReceiptNoteType",
    "GoodsReceiptNoteWrite",
    "GoodsReceiptPurchaseOrderReport",
    "GoodsReceiptRegisterRecord",
    "GoodsReceiptResponse",
    "GoodsReceiptStatus",
    "GoodsReceiptSummary",
    "GoodsReceiptUpdate",
]
