"""Validated contracts for sales returns."""

from app.sales_return.schemas.sales_return import (
    SalesReturnAttachmentResponse,
    SalesReturnAttachmentWrite,
    SalesReturnByCustomerRecord,
    SalesReturnByProductRecord,
    SalesReturnCreate,
    SalesReturnImportRequest,
    SalesReturnLineResponse,
    SalesReturnLineWrite,
    SalesReturnListFilters,
    SalesReturnNoteResponse,
    SalesReturnNoteWrite,
    SalesReturnReconciliationRecord,
    SalesReturnRegisterRecord,
    SalesReturnResponse,
    SalesReturnSourceResponse,
    SalesReturnSourceType,
    SalesReturnSourceWrite,
    SalesReturnStatus,
    SalesReturnSummary,
    SalesReturnUpdate,
)

__all__ = [
    "SalesReturnAttachmentResponse",
    "SalesReturnAttachmentWrite",
    "SalesReturnByCustomerRecord",
    "SalesReturnByProductRecord",
    "SalesReturnCreate",
    "SalesReturnImportRequest",
    "SalesReturnLineResponse",
    "SalesReturnLineWrite",
    "SalesReturnListFilters",
    "SalesReturnNoteResponse",
    "SalesReturnNoteWrite",
    "SalesReturnReconciliationRecord",
    "SalesReturnRegisterRecord",
    "SalesReturnResponse",
    "SalesReturnSourceResponse",
    "SalesReturnSourceType",
    "SalesReturnSourceWrite",
    "SalesReturnStatus",
    "SalesReturnSummary",
    "SalesReturnUpdate",
]
