"""Document lifecycle framework schemas."""

from app.document_framework.schemas.document_framework import (
    DocumentApprovalContract,
    DocumentAttachmentContract,
    DocumentEmailContract,
    DocumentFrameworkSchema,
    DocumentHeaderContract,
    DocumentLifecycleEventCreate,
    DocumentLifecycleEventResponse,
    DocumentLineContract,
    DocumentNoteContract,
    DocumentNumberingRuleCreate,
    DocumentNumberingRuleResponse,
    DocumentNumberingRuleUpdate,
    DocumentPdfContract,
    DocumentPrintContract,
    DocumentStateCreate,
    DocumentStateResponse,
    DocumentStateUpdate,
    DocumentTimelineEntry,
    DocumentTotalsContract,
    DocumentTypeCreate,
    DocumentTypeResponse,
    DocumentTypeUpdate,
)

__all__ = [
    "DocumentApprovalContract",
    "DocumentAttachmentContract",
    "DocumentEmailContract",
    "DocumentFrameworkSchema",
    "DocumentHeaderContract",
    "DocumentLifecycleEventCreate",
    "DocumentLifecycleEventResponse",
    "DocumentLineContract",
    "DocumentNoteContract",
    "DocumentNumberingRuleCreate",
    "DocumentNumberingRuleResponse",
    "DocumentNumberingRuleUpdate",
    "DocumentPdfContract",
    "DocumentPrintContract",
    "DocumentStateCreate",
    "DocumentStateResponse",
    "DocumentStateUpdate",
    "DocumentTimelineEntry",
    "DocumentTotalsContract",
    "DocumentTypeCreate",
    "DocumentTypeResponse",
    "DocumentTypeUpdate",
]
